version: "3.9"
services:
  dev-edms:
    image: botech/dev-edms
    build:
      context: .
      dockerfile: ./dev-edms.Dockerfile
    entrypoint: /bin/sh -c
    command:
      - |
        . ~/venv/bin/activate
        ~/src/mayan-edms/manage.py runserver --settings=botech.edms_dev.settings 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ../:/home/mayan/src/botech-edms
      - ../../../wo/mayan-edms/:/home/mayan/src/mayan-edms
      - ../.venv/:/home/mayan/venv
      # - logvolume01:/var/log
  #   depends_on:
  #     - redis
  # redis:
  #   image: redis
# volumes:
#   logvolume01: {}
